version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordlynx
    container_name: nordlynx
    cap_add:
      - NET_ADMIN               # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - PRIVATE_KEY=IF1FGVSzrUznFVZ+dymIz+6bdlCgsuiT/d6cyapN8lw=    # Required
      # - CONNECT=Spain
      - NET_LOCAL=192.168.31.0/24  # So it can be accessed within the local network
    ports:
      - 80:8080
      - 6881:6881
      - 6881:6881/udp
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
  torrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    volumes:
      - /home/pi/bit-torrent/config:/config
      - /home/pi/bit-torrent/torrents:/torrents
      - /home/pi/share:/downloads
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: service:vpn
    depends_on:
      - vpn